be sure to search only *R3D.dv files

diff --git a/omero_importer b/omero_importer
--- a/omero_importer
+++ b/omero_importer
@@ -3,12 +3,8 @@
 # checking whether OMERO is running
 omero login -s localhost -u suguru -w omx > /dev/null 2> /dev/null
 if [ "$?" -ne 0 ]; then
-    su -c "omero admin start" pcarlton
-    omero login -s localhost -u suguru -w omx > /dev/null 2> /dev/null
-    if [ $? -ne 0 ]; then
-        echo '[ERROR] OMERO.server is not running.'
-        exit 1
-    fi
+    echo '[ERROR] OMERO.server is not running.'
+    exit 1
 fi
 omero logout
 
